---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oci-la-fluentd.name" . }}-logs-clusterrole
  namespace: {{ default "kube-system" .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch