apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oci-la-fluentd.name" . }}-objects-configmap
  namespace: {{ default "kube-system" .Values.namespace }}
data:
  # file-like keys
  {{- range $key, $value := .Values.fluentd.configMapObjectsFiles }}
  {{ $key }}: |
    {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 4 }}
  {{- end }}